version: '3.7'
services:
  tg-store-bot:
    container_name: tg-store-bot
    restart: always
    build: .
    volumes:
      - './packages/client/src:/app/packages/client/src'
      - './packages/server/src:/app/packages/server/src'
      - './packages/server/prisma:/app/packages/server/prisma'
      - './packages/server/schema.graphql:/app/packages/server/schema.graphql'
    ports:
      - '443:443'
      - '5555:5555'
    env_file:
      - .env.development
    networks:
      - mynetwork
    depends_on:
      - db-store
  db-store:
    container_name: db-store
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    